In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("C:\\Users\\Pranav Mahesh\\Downloads\\homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']].values, df.price)

LinearRegression()

In [4]:
reg.predict([[3300]])

array([628715.75342466])

In [5]:
import pickle

In [6]:
with open('module_pickle', 'wb')as f:
    pickle.dump(reg, f)

In [8]:
with open('module_pickle', 'rb') as f:
    mp = pickle.load(f)

In [10]:
mp.predict([[3300]])

array([628715.75342466])

In [13]:
import joblib

In [14]:
joblib.dump(reg, 'module_joblib')

['module_joblib']

In [16]:
mj = joblib.load('module_joblib')
mj.predict([[3300]])

array([628715.75342466])